[package]
name = "rustrings"
version = "1.0.0"
edition = "2021"
description = "Strings manipulation for Rust"
license = "MIT"
repository = "https://github.com/MCausc78/rustrings"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
